{   '2mm': {   'ariel_markers': True,
               'cmd': '2mm',
               'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/2mm'},
    '3mm': {   'ariel_markers': True,
               'cmd': '3mm',
               'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/3mm'},
    'adi': {   'ariel_markers': True,
               'cmd': 'adi',
               'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/adi'},
    'atax': {   'ariel_markers': True,
                'cmd': 'atax',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/atax'},
    'bicg': {   'ariel_markers': True,
                'cmd': 'bicg',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/bicg'},
    'cholesky': {   'ariel_markers': True,
                    'cmd': 'cholesky',
                    'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/cholesky'},
    'correlation': {   'ariel_markers': True,
                       'cmd': 'correlation',
                       'directory': '/nethome/plavin3/sst/polybench/polybench-code/datamining/correlation'},
    'covariance': {   'ariel_markers': True,
                      'cmd': 'covariance',
                      'directory': '/nethome/plavin3/sst/polybench/polybench-code/datamining/covariance'},
    'deriche': {   'ariel_markers': True,
                   'cmd': 'deriche',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/medley/deriche'},
    'doitgen': {   'ariel_markers': True,
                   'cmd': 'doitgen',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/doitgen'},
    'durbin': {   'ariel_markers': True,
                  'cmd': 'durbin',
                  'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/durbin'},
    'fdtd-2d': {   'ariel_markers': True,
                   'cmd': 'fdtd-2d',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/fdtd-2d'},
    'floyd-warshall': {   'ariel_markers': True,
                          'cmd': 'floyd-warshall',
                          'directory': '/nethome/plavin3/sst/polybench/polybench-code/medley/floyd-warshall'},
    'gemm': {   'ariel_markers': True,
                'cmd': 'gemm',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/gemm'},
    'gemver': {   'ariel_markers': True,
                  'cmd': 'gemver',
                  'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/gemver'},
    'gesummv': {   'ariel_markers': True,
                   'cmd': 'gesummv',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/gesummv'},
    'gramschmidt': {   'ariel_markers': True,
                       'cmd': 'gramschmidt',
                       'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/gramschmidt'},
    'heat-3d': {   'ariel_markers': True,
                   'cmd': 'heat-3d',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/heat-3d'},
    'jacobi-1d': {   'ariel_markers': True,
                     'cmd': 'jacobi-1d',
                     'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/jacobi-1d'},
    'jacobi-2d': {   'ariel_markers': True,
                     'cmd': 'jacobi-2d',
                     'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/jacobi-2d'},
    'lu': {   'ariel_markers': True,
              'cmd': 'lu',
              'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/lu'},
    'ludcmp': {   'ariel_markers': True,
                  'cmd': 'ludcmp',
                  'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/ludcmp'},
    'mvt': {   'ariel_markers': True,
               'cmd': 'mvt',
               'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/mvt'},
    'nussinov': {   'ariel_markers': True,
                    'cmd': 'nussinov',
                    'directory': '/nethome/plavin3/sst/polybench/polybench-code/medley/nussinov'},
    'seidel-2d': {   'ariel_markers': True,
                     'cmd': 'seidel-2d',
                     'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/seidel-2d'},
    'symm': {   'ariel_markers': True,
                'cmd': 'symm',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/symm'},
    'syr2k': {   'ariel_markers': True,
                 'cmd': 'syr2k',
                 'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/syr2k'},
    'syrk': {   'ariel_markers': True,
                'cmd': 'syrk',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/syrk'},
    'trisolv': {   'ariel_markers': True,
                   'cmd': 'trisolv',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/trisolv'},
    'trmm': {   'ariel_markers': True,
                'cmd': 'trmm',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/trmm'}}
