{   'atax': {   'ariel_markers': False,
                'cmd': 'atax',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/atax'},
    'bicg': {   'ariel_markers': False,
                'cmd': 'bicg',
                'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/bicg'},
    'deriche': {   'ariel_markers': False,
                   'cmd': 'deriche',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/medley/deriche'},
    'durbin': {   'ariel_markers': False,
                  'cmd': 'durbin',
                  'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/durbin'},
    'gemver': {   'ariel_markers': False,
                  'cmd': 'gemver',
                  'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/gemver'},
    'gesummv': {   'ariel_markers': False,
                   'cmd': 'gesummv',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/blas/gesummv'},
    'jacobi-1d': {   'ariel_markers': False,
                     'cmd': 'jacobi-1d',
                     'directory': '/nethome/plavin3/sst/polybench/polybench-code/stencils/jacobi-1d'},
    'mvt': {   'ariel_markers': False,
               'cmd': 'mvt',
               'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/kernels/mvt'},
    'trisolv': {   'ariel_markers': False,
                   'cmd': 'trisolv',
                   'directory': '/nethome/plavin3/sst/polybench/polybench-code/linear-algebra/solvers/trisolv'}}
